language: r
r:
  - oldrel
  - release
  - devel
  
jobs:
  include:
  - r: oldrel
    warnings_are_errors: false
  - r: release
    warnings_are_errors: false
  - r: devel
    warnings_are_errors: false
    
global:
  - _R_CHECK_FORCE_SUGGESTS_: false
  
 apt:
    packages:
      - gdal-bin
      - libgdal1-dev
      - libproj-dev
      - libudunits2-dev

    
r_packages:
  - covr
  
r_binary_packages:
  - rgdal
  
  
after_success:
  - Rscript -e 'library(covr); codecov()'
  

#before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
#deploy:
#  provider: script
#  script: Rscript -e 'pkgdown::deploy_site_github()'
#  skip_cleanup: true