language: r
r:
  - oldrel
  - release
  - devel

warnings_are_errors: false

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal1-dev
      - libproj-dev
      - libgsl0-dev
      - libudunits2-dev

jobs:
  include:
  - r: release
    warnings_are_errors: false
  - r: devel
    warnings_are_errors: false


r_packages:
  - covr
  
r_binary_packages:
  - rgdal


#before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
#deploy:
#  provider: script
#  script: Rscript -e 'pkgdown::deploy_site_github()'
#  skip_cleanup: true